# -*- coding: utf-8 -*-
'''
Chapter "魔獣"
'''
import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '../..'))
sys.path.append('storybuilder')
from storybuilder.builder.world import World
from config import TITLES


## chapter
def main(w: World):
    return w.chapter(TITLES[5],
            w.plot_setup("魔獣伝説のある場所で猟奇殺人事件が起こる"),
            w.plot_turnpoint("$sherlockの許にその孤島のパーティの招待状が届く"),
            w.plot_develop("$restradeの弟から事件解明を頼まれる"),
            w.plot_turnpoint("最初の殺人事件が起こる"),
            w.plot_develop("海は荒れて脱出も不可能になり、招待客は島に閉じ込められる"),
            w.plot_turnpoint("第二の被害者が出る"),
            w.plot_develop("$sherlockは獣による犯行ではないとして調査を開始する"),
            w.plot_turnpoint("本物の魔獣が出現する"),
            w.plot_develop("魔獣を殺そうとするが女主人が体を張って守ろうとする"),
            w.plot_turnpoint("$sherlockは女主人が犯人だと説明する"),
            w.plot_develop("女主人は魔獣とともに脱出を試みる"),
            w.plot_turnpoint("魔獣は女主人を食べてしまった"),
            w.plot_resolve("蘇りの秘法を使って$boss復活を願う宗教団体だったと判明する"),
            "魔獣の伝説",
            w.plot_note("朝食をとっているところで、幽霊や怪奇現象についての話題が出る"),
            w.plot_note("$sherlockは不可思議な現象を信じない"),
            w.plot_note("かつていたとされている闇の世界の住人も、多くは現実にあったことが歪んで伝えられたのだと言ってのける"),
            w.plot_note("そこにドアがノックされ、男が現れる"),
            "調査依頼",
            w.plot_note("男は$Dartmourから来たといった"),
            w.plot_note("その土地では古くから巨大な犬の伝説があり、住民に恐れられていた"),
            w.plot_note("この半年ほどの間にペットの犬や猟犬が怪死するということが続いていて、半月前にはついに人間の被害者が出たらしい"),
            w.plot_note("現在は三人が被害者になり、引っ越して街を脱出する人間まで現れた"),
            w.plot_note("地元の観光協会は事態を大変重く見て、こうして問題解決のスペシャリストの$sherlockに依頼にきたという訳だ"),
            w.plot_note("$sherlockは魔獣の伝説は信じないが、実際に被害者が出ている事件だから捜査をしようと引き受ける"),
            "$Dartmour",
            w.plot_note("$trainで$Dartmourへと移動する"),
            w.plot_note("$maryたちは軽い旅行気分"),
            w.plot_note("$sherlockはその間に起こっている事件の資料と地域の情報を頭に入れておく"),
            w.plot_note("昔に荘園主が建てた邸宅があり、そこの主が恋をした娘を監禁した"),
            w.plot_note("しかし娘は逃げ出した"),
            w.plot_note("その娘を追わせるために飼っていた犬を放った"),
            w.plot_note("娘を食い殺した犬は、しかし、その飼い主である主をも食い殺してしまったのだ"),
            w.plot_note("猟銃すらきかず、野に放たれた魔獣は今でもこの荒野のどこかをうろついては、家に関わるものを呪い殺そうとしていると言われている"),
            w.plot_note("虫けらのように猟犬を扱っていた主への怨念だとも言われているし、こきつかわれた猟師や小作人、使用人たちが殺したんだとも"),
            "観光協会",
            w.plot_note("駅に到着すると迎えに来ていた観光協会の人間について、まずは事務所に向かう"),
            w.plot_note("観光協会の地図を見ながら、事件のあった場所や、その血筋の生き残りの女性が一人で暮らす家の場所を教わる"),
            w.plot_note("魔獣の伝説のせいで浮いているその女性$cherryの家に向かう$sherlock"),
            "$ln_cherry家の呪い",
            w.plot_note("家は沼地を超えた先にあった"),
            w.plot_note("家を訪れると未亡人となった婦人が出迎えてくれた"),
            w.plot_note("家には彼女以外誰もいないらしい"),
            w.plot_note("魔獣の伝説があるが恐くないのか、と尋ねると生まれる前からずっとそうだったと"),
            w.plot_note("どことなく上の空な雰囲気"),
            w.plot_note("一旦家をあとにする"),
            "殺人事件",
            w.plot_note("翌朝、観光協会の$mochが殺されている姿で発見された"),
            w.plot_note("$sherlockは地元警察の応援にやってきた$restradeに協力をしてもらい、情報をもらう"),
            w.plot_note("事件は今までと同じで、とても人間に襲われたそれとは思えない"),
            w.plot_note("完全に大型の動物による犯行にしか思えなかった"),
            w.plot_note("警察は周囲に非常網を張る"),
            w.plot_note("$sherlockは$mochの言動に怪しいところがあると、彼のことを調べ始める"),
            "宗教団体",
            w.plot_note("$mochがある宗教団体に属していたことが分かり、そこの支部を調べる"),
            w.plot_note("近年国内で信者を獲得している新興教団で、古来の技術の復活と礼賛を基本にしている"),
            w.plot_note("新しい$enagy技術は大地の力を浪費するばかりで、そのうちに世界が枯れ果てると言う"),
            w.plot_note("環境にもよくないから昔の生活をしよう、という主張のようだ"),
            w.plot_note("その会員の中に$cherryの名前を見つける"),
            "隠された獣",
            w.plot_note("$cherryの家に向かい、$sherlockは気になっていたものを調べる"),
            w.plot_note("この家に人ではなく、獣がいませんかと"),
            w.plot_note("彼女はいないと言い張るが、黒い毛がいたるところで見つかり、言い逃れできなくなる"),
            w.plot_note("そこに襲いかかってくる黒い巨大な犬"),
            w.plot_note("それはまさに魔獣だった"),
            w.plot_note("しかし彼女はそれを身体を張って守ろうとする"),
            w.plot_note("彼女の愛犬だというのだ"),
            w.plot_note("$maryはその犬が犯人かと尋ねるが、$sherlockは否定する"),
            w.plot_note("「あなたがやったんですね？$cherryさん」と"),
            "告白",
            w.plot_note("$sherlockは人間ではなくそれまでにたくさんの犬が殺されていた方に着目していた"),
            w.plot_note("動物を人間の代わりに殺す人間はごくまれにいる"),
            w.plot_note("裏に小さなお墓があった。それが$cherryが最初に殺した犬だという"),
            w.plot_note("「自分の愛犬を殺しましたね？」と"),
            w.plot_note("$cherryは事情を語る"),
            w.plot_note("自分の飼っていた犬が夫によって体を悪くしてしまい、それを見かねて殺してしまった"),
            w.plot_note("その頃に夫が事故死しているのは、$cherryが仕組んだもの"),
            w.plot_note("愛犬を復活させる術をある人物からきいて、それを実行した。それに大量の財産をぶちこんだ"),
            w.plot_note("愛犬は生き返った。しかし生きながらえるために他の命を食う必要があった"),
            w.plot_note("最初は野犬を殺して回った"),
            w.plot_note("しかしそのうちにすぐ空腹になるようになった"),
            w.plot_note("人間を食らうと長生きすると知る"),
            w.plot_note("一人を殺して与えたら、大人しくなった"),
            w.plot_note("そこから先は説明するまでもない。この先もずっと誰かを殺して食べさせるつもりだと語った"),
            "事後報告",
            w.plot_note("事件は$cherryが逮捕されて解決を見た"),
            w.plot_note("しかし後味のすっきりしなさに$maryは落ち込む"),
            w.plot_note("それから情報屋経由で最後の一つの宝石を彼女が持っていて、それを売り払っていたことを知る"),
            w.plot_note("$sherlockはこれで相手に四つの$stoneが揃ったと考えた"),
            )


